version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"

  - package-ecosystem: "bundler"
    directory: "/apps/epp_proxy/priv/test_backend_app"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"

  - package-ecosystem: "hex"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"
