FROM debian:bookworm-slim AS build

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
COPY ./docker/apt/sources.list /etc/apt/

RUN apt-get update && apt-get install -y -qq \
  wget \
  git \
  build-essential \
  automake \
  autoconf \
  curl \
  ca-certificates \
  libssl3 \
  libssl-dev \
  libreadline-dev \
  libdpkg-perl \
  liberror-perl \
  libc6 \
  libc-dev \
  perl \
  procps \
  inotify-tools \
  perl-base \
  zlib1g-dev \
  libncurses-dev \
  libsctp-dev \
  xsltproc \
  libxml2-utils \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ENV KERL_CONFIGURE_OPTIONS="--disable-debug --without-javac --without-wx --without-odbc --disable-hipe --without-jinterface --without-docs"
ENV KERL_BUILD_DOCS="no"
ENV KERL_DOC_TARGETS=""
ENV KERL_INSTALL_HTMLDOCS="no"
ENV KERL_INSTALL_MANPAGES="no"

RUN git clone https://github.com/asdf-vm/asdf.git --branch v0.14.0 "$HOME"/.asdf && \
    echo '. $HOME/.asdf/asdf.sh' >> "$HOME"/.bashrc && \
    echo '. $HOME/.asdf/asdf.sh' >> "$HOME"/.profile

ENV PATH="${PATH}:/root/.asdf/shims:/root/.asdf/bin"

RUN mkdir -p /opt/erlang/epp_proxy
WORKDIR /opt/erlang/epp_proxy

ENV GIT_TERMINAL_PROMPT=0

COPY .tool-versions ./
RUN . "$HOME"/.asdf/asdf.sh && \
    asdf plugin add erlang && \
    asdf plugin add rebar && \
    asdf install erlang "$(grep erlang .tool-versions | awk '{print $2}')" && \
    asdf install rebar "$(grep rebar .tool-versions | awk '{print $2}')" && \
    asdf global erlang "$(grep erlang .tool-versions | awk '{print $2}')" && \
    asdf global rebar "$(grep rebar .tool-versions | awk '{print $2}')"

COPY rebar.config rebar.lock ./
COPY config ./config
COPY apps ./apps

RUN . "$HOME"/.asdf/asdf.sh && rebar3 as prod release

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y -qq \
  libssl3 \
  libncurses6 \
  libsctp1 \
  procps \
  ca-certificates \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/erlang/epp_proxy
WORKDIR /opt/erlang/epp_proxy

COPY --from=build /opt/erlang/epp_proxy/_build/prod/rel/epp_proxy ./

RUN groupadd -r epp && useradd -r -g epp epp
RUN chown -R epp:epp /opt/erlang/epp_proxy
USER epp

EXPOSE 700

ENV RELX_REPLACE_OS_VARS=true
ENV NODE_NAME=epp_proxy@127.0.0.1

CMD ["./bin/epp_proxy", "foreground"]
