FROM debian:bookworm-slim

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
COPY ./docker/apt/sources.list /etc/apt/

RUN apt-get update && apt-get install -y -qq \
  wget \
  git \
  build-essential \
  automake \
  autoconf \
  curl \
  ca-certificates \
  libssl3 \
  libssl-dev \
  libreadline-dev \
  libdpkg-perl \
  liberror-perl \
  libc6 \
  libc-dev \
  perl \
  procps \
  inotify-tools \
  perl-base \
  zlib1g-dev \
  libncurses-dev \
  libsctp-dev \
  xsltproc \
  libxml2-utils \
  libffi-dev \
  libyaml-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ENV KERL_CONFIGURE_OPTIONS="--disable-debug --without-javac --without-wx --without-odbc --disable-hipe --without-jinterface --without-docs"
ENV KERL_BUILD_DOCS="no"
ENV KERL_DOC_TARGETS=""
ENV KERL_INSTALL_HTMLDOCS="no"
ENV KERL_INSTALL_MANPAGES="no"

RUN git clone https://github.com/asdf-vm/asdf.git --branch v0.14.0 "$HOME"/.asdf && \
    echo '. $HOME/.asdf/asdf.sh' >> "$HOME"/.bashrc && \
    echo '. $HOME/.asdf/asdf.sh' >> "$HOME"/.profile

ENV PATH="${PATH}:/root/.asdf/shims:/root/.asdf/bin"
ENV GIT_TERMINAL_PROMPT=0

RUN mkdir -p /opt/erlang/epp_proxy
WORKDIR /opt/erlang/epp_proxy

COPY .tool-versions ./
RUN . "$HOME"/.asdf/asdf.sh && \
    asdf plugin add erlang && \
    asdf plugin add ruby && \
    asdf plugin add rebar && \
    asdf install && \
    asdf global erlang "$(grep erlang .tool-versions | awk '{print $2}')" && \
    asdf global ruby "$(grep ruby .tool-versions | awk '{print $2}')" && \
    asdf global rebar "$(grep rebar .tool-versions | awk '{print $2}')"

COPY . .

CMD ["tail", "-f", "/dev/null"]
