#!/bin/bash

case $1 in
    help)
        echo "bin/epp_proxy reload"
        ;;
    *)
        ;;
esac

# Kill TLS acceptor, it should return OK
Status=$(relx_nodetool eval "exit(whereis(epp_tls_acceptor), normal).")

# now print the status back
code="io:format(\"~p~n\", [$Status]),
      halt()."
echo $(erl -boot no_dot_erlang -sasl errlog_type error -noshell -eval "$code")
