name: build and push image

on: [push]
  # push:
  #   paths:
  #   - .tool-versions

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - name: Set image tag
      shell: python
      run: |
        import os
        versions = {}
        try:
            with open(".tool-versions", "r") as f:
                for line in f:
                (key, val) = line.split()
                versions[key] = val
        except:
            print("Something is not right")
        print("internetee/erlang-ruby:" + versions["erlang"] + "-" + versions["ruby"])
        print(os.environ["GITHUB_ENV"])
        #echo "TAG=internetee/erlang-ruby:'$ERLANG_VER'-'$RUBY_VER'" >> $GITHUB_ENV

    - name: Build image
      run: |
        docker build -t $TAG -f Dockerfile.Erlang-ruby.base .

    - name: Push image to Docker hub
      env:
        D_HUB_PASS: ${{ secrets.D_HUB_PASS}}
      run: |
        echo $D_HUB_PASS | docker login -u eiskra --password-stdin
        docker push $TAG
