name: Proxy automated tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.0.0

      - name: Build image for tests
        run: docker build -t proxy-tester -f Dockerfile.test . 

      - name: Start the container
        run: docker run -d --name tester proxy-tester
      
      - name: Install rebar dependencies
        run: docker exec -i tester rebar3 as test get-deps

      - name: Integrated Ruby app setup
        run: docker exec -i tester apps/epp_proxy/priv/test_backend_app && bundle install && bundle exec rackup

      - name: Compile for tests
        run: docker exec -i tester rebar3 as test compile